[package]
name = "light-please"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
eyre = "0.6.8"
softbuffer = "0.4.2"
winit = "0.29.15"
